In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\TECQNIO\Downloads\income (1).csv")

In [5]:
df.head()

age       JobType         EdType        maritalstatus       occupation  \
0   45       Private        HS-grad             Divorced     Adm-clerical   
1   24   Federal-gov        HS-grad        Never-married     Armed-Forces   
2   44       Private   Some-college   Married-civ-spouse   Prof-specialty   
3   27       Private            9th        Never-married     Craft-repair   
4   20       Private   Some-college        Never-married            Sales   

      relationship    race   gender  capitalgain  capitalloss  hoursperweek  \
0    Not-in-family   White   Female            0            0            28   
1        Own-child   White     Male            0            0            40   
2          Husband   White     Male            0            0            40   
3   Other-relative   White     Male            0            0            40   
4    Not-in-family   White     Male            0            0            35   

    nativecountry                        SalStat  
0   United-States   less than or equal to 50,000  
1   United-States   less than or equal to 50,000  
2   United-States            greater than 50,000  
3          Mexico   less than or equal to 50,000  
4   United-States   less than or equal to 50,000

In [6]:
df.columns

Index(['age', 'JobType', 'EdType', 'maritalstatus', 'occupation',
       'relationship', 'race', 'gender', 'capitalgain', 'capitalloss',
       'hoursperweek', 'nativecountry', 'SalStat'],
      dtype='object')

In [7]:
df.drop(['maritalstatus', 'relationship', 'race', 'gender', 'nativecountry'],axis='columns',inplace=True)

In [8]:
df.shape

(31978, 8)

In [9]:
df.head()

age       JobType         EdType       occupation  capitalgain  \
0   45       Private        HS-grad     Adm-clerical            0   
1   24   Federal-gov        HS-grad     Armed-Forces            0   
2   44       Private   Some-college   Prof-specialty            0   
3   27       Private            9th     Craft-repair            0   
4   20       Private   Some-college            Sales            0   

   capitalloss  hoursperweek                        SalStat  
0            0            28   less than or equal to 50,000  
1            0            40   less than or equal to 50,000  
2            0            40            greater than 50,000  
3            0            40   less than or equal to 50,000  
4            0            35   less than or equal to 50,000

In [10]:
df.nunique()

age              73
JobType           9
EdType           16
occupation       15
capitalgain     119
capitalloss      92
hoursperweek     94
SalStat           2
dtype: int64

In [11]:
df.tail()

age     JobType         EdType        occupation  capitalgain  \
31973   34   Local-gov        HS-grad   Farming-fishing          594   
31974   34   Local-gov   Some-college   Protective-serv            0   
31975   23     Private   Some-college      Adm-clerical            0   
31976   42   Local-gov   Some-college      Adm-clerical            0   
31977   29     Private      Bachelors    Prof-specialty            0   

       capitalloss  hoursperweek                        SalStat  
31973            0            60   less than or equal to 50,000  
31974            0            40   less than or equal to 50,000  
31975            0            40   less than or equal to 50,000  
31976            0            40   less than or equal to 50,000  
31977            0            40   less than or equal to 50,000

In [12]:
df.sample(30)

age            JobType         EdType          occupation  capitalgain  \
14794   51            Private        HS-grad        Adm-clerical            0   
10458   41   Self-emp-not-inc      Assoc-voc               Sales            0   
17521   55            Private   Some-college               Sales            0   
29408   61            Private           12th        Craft-repair            0   
18586   48            Private        HS-grad        Craft-repair            0   
3145    34            Private      Bachelors     Exec-managerial        15024   
4184    26            Private   Some-college        Craft-repair            0   
27670   37            Private   Some-college        Adm-clerical            0   
11403   22            Private        HS-grad        Craft-repair            0   
25913   37            Private      Assoc-voc               Sales            0   
31960   29            Private        HS-grad     Farming-fishing            0   
8278    53        Federal-gov        HS-grad        Adm-clerical         7688   
11763   57            Private      Assoc-voc        Craft-repair            0   
30565   36            Private        HS-grad        Tech-support            0   
17926   20            Private        HS-grad   Machine-op-inspct            0   
30719   39            Private        HS-grad        Adm-clerical            0   
5287    78                  ?        Masters                   ?            0   
8961    36   Self-emp-not-inc      Bachelors               Sales         2174   
7169    68            Private   Some-college     Priv-house-serv            0   
19174   56            Private           11th       Other-service            0   
12599   30            Private        HS-grad               Sales            0   
23145   25            Private   Some-college      Prof-specialty         8614   
1059    47          Local-gov      Bachelors     Protective-serv            0   
13287   39            Private           11th      Prof-specialty            0   
8641    26            Private        HS-grad        Adm-clerical            0   
8316    26            Private   Some-college   Handlers-cleaners            0   
27350   27   Self-emp-not-inc   Some-college       Other-service            0   
20628   32            Private        HS-grad   Machine-op-inspct            0   
18309   21            Private   Some-college        Adm-clerical            0   
24956   36   Self-emp-not-inc      Bachelors               Sales            0   

       capitalloss  hoursperweek                        SalStat  
14794            0            40   less than or equal to 50,000  
10458            0            60   less than or equal to 50,000  
17521            0            50   less than or equal to 50,000  
29408            0            40   less than or equal to 50,000  
18586            0            40   less than or equal to 50,000  
3145             0            60            greater than 50,000  
4184             0            43   less than or equal to 50,000  
27670            0            37   less than or equal to 50,000  
11403            0            36   less than or equal to 50,000  
25913            0            54   less than or equal to 50,000  
31960            0            40   less than or equal to 50,000  
8278             0            35            greater than 50,000  
11763            0            40            greater than 50,000  
30565            0            50   less than or equal to 50,000  
17926            0            45   less than or equal to 50,000  
30719            0            40   less than or equal to 50,000  
5287             0            15   less than or equal to 50,000  
8961             0            50   less than or equal to 50,000  
7169             0            30   less than or equal to 50,000  
19174            0            40   less than or equal to 50,000  
12599            0            35   less than or equal to 50,000  
23145            0            40           

In [13]:
df.columns

Index(['age', 'JobType', 'EdType', 'occupation', 'capitalgain', 'capitalloss',
       'hoursperweek', 'SalStat'],
      dtype='object')

In [14]:
df['age'].unique()

array([45, 24, 44, 27, 20, 51, 17, 19, 60, 40, 30, 38, 23, 32, 54, 50, 37,
       52, 49, 22, 35, 67, 46, 33, 43, 28, 41, 25, 63, 59, 34, 26, 72, 62,
       58, 47, 39, 53, 57, 21, 42, 74, 36, 29, 31, 69, 18, 65, 55, 48, 71,
       70, 66, 56, 61, 68, 64, 73, 81, 78, 76, 90, 88, 75, 77, 80, 82, 79,
       83, 84, 85, 86, 87], dtype=int64)

In [15]:
df['EdType'].unique()

array([' HS-grad', ' Some-college', ' 9th', ' 11th', ' Assoc-voc',
       ' Assoc-acdm', ' Bachelors', ' 1st-4th', ' Masters', ' 10th',
       ' 12th', ' 5th-6th', ' Prof-school', ' Doctorate', ' 7th-8th',
       ' Preschool'], dtype=object)

In [16]:
df['occupation'].unique()

array([' Adm-clerical', ' Armed-Forces', ' Prof-specialty',
       ' Craft-repair', ' Sales', ' Exec-managerial',
       ' Machine-op-inspct', ' ?', ' Transport-moving',
       ' Farming-fishing', ' Tech-support', ' Other-service',
       ' Handlers-cleaners', ' Protective-serv', ' Priv-house-serv'],
      dtype=object)

In [17]:
df['capitalgain'].unique()

array([    0,   594, 15024,  7688, 20051,  5013,  2174,  6849,  1055,
        5178,  4101,  1111,  8614,  3411,  2597, 25236,  4386,  4650,
        7298,  2407, 14084,  2463,  3103, 10605,  2964,  3325,  2580,
        3471,  4865, 99999,  6514,  1471,  3674,  2329,  2105,  2885,
       25124,  2176, 10520,  2202,  2961, 27828,  6767,  2228,  1506,
       13550,  1409,  2635,  5556, 14344,  4787,  3781,  3137,  3818,
         914,  4064,   401,  2829,  2977,  4934,  2062,  2354,  3464,
        5455, 15020,  1424,  3273, 22040,  4416,  3908, 10566,   991,
        4931,  1086,  7430, 34095,  6497,   114,  9386,  2346,  3418,
        3432,  2907,  1151,  2414,  2290, 15831, 41310,  4508,  2050,
        2538,  3456,  6418,  1848,  3887,  7896,  5721,  9562,  1455,
        2036,  3942,  1831, 11678,  2936,  2993,  7443,  6360,  1797,
        1173,  4687,  6723,  2009,  6097,  2653,  1639, 18481,  7978,
        2387,  5060], dtype=int64)

In [18]:
df['capitalloss'].unique()

array([   0, 1977, 1380, 1887, 1902, 1762, 1721, 2051, 2377, 1669, 2352,
       1672,  653, 2415, 2392, 1504, 1719, 2001, 1590, 1651, 1876, 1628,
       1848, 1564, 1980, 1340, 2339, 1740, 2002, 1579, 1741, 1408, 2258,
       1485, 1602,  419, 2547, 2174, 2206, 2205, 1726, 2444, 1138, 2238,
       2179,  625,  213, 1816, 1539,  880, 1668, 1092, 1594, 2042, 2231,
       1844,  810, 2824, 2559, 2057, 1573, 1974,  974, 2149, 1825, 1735,
       1258, 2603, 2282,  323, 4356, 2246, 1617, 1648, 2489, 3770, 1755,
       3683, 2129, 2267, 2080, 2457,  155, 3900, 2201, 1944, 2467, 2163,
       2754, 2472, 3004, 1411], dtype=int64)

In [19]:
df['hoursperweek'].unique()

array([28, 40, 35,  5, 55, 50, 60, 20, 45, 16, 24,  6, 30, 25, 36, 42,  8,
       38, 80, 58,  9, 46, 48, 32, 12, 70, 47, 37, 21, 64, 26, 14, 15, 10,
        4, 65, 72, 18, 56, 33, 75,  7, 52, 44, 99, 43,  2, 53, 39, 54, 62,
       41, 59,  1, 57, 78, 90, 34, 66, 11, 49, 84,  3, 17, 68, 22, 27, 13,
       98, 85, 31, 51, 77, 63, 23, 87, 88, 73, 89, 97, 19, 94, 29, 96, 67,
       82, 86, 91, 81, 76, 92, 61, 74, 95], dtype=int64)

In [20]:
df['SalStat'].unique()

array([' less than or equal to 50,000', ' greater than 50,000'],
      dtype=object)

In [21]:
df.isnull().sum()

age             0
JobType         0
EdType          0
occupation      0
capitalgain     0
capitalloss     0
hoursperweek    0
SalStat         0
dtype: int64

In [22]:
import numpy as np
missing_values=[np.nan,'?']
df=pd.read_csv(r"C:\Users\TECQNIO\Downloads\income (1).csv",na_values=missing_values)

In [23]:
df.isnull().sum()

age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64

In [25]:
df.shape

(31978, 13)

In [26]:
df.dropna(inplace=True)

In [27]:
df.isnull().sum()

age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31978 entries, 0 to 31977
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            31978 non-null  int64 
 1   JobType        31978 non-null  object
 2   EdType         31978 non-null  object
 3   maritalstatus  31978 non-null  object
 4   occupation     31978 non-null  object
 5   relationship   31978 non-null  object
 6   race           31978 non-null  object
 7   gender         31978 non-null  object
 8   capitalgain    31978 non-null  int64 
 9   capitalloss    31978 non-null  int64 
 10  hoursperweek   31978 non-null  int64 
 11  nativecountry  31978 non-null  object
 12  SalStat        31978 non-null  object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB


In [29]:
df.drop(['maritalstatus', 'relationship', 'race', 'gender', 'nativecountry'],axis='columns',inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31978 entries, 0 to 31977
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           31978 non-null  int64 
 1   JobType       31978 non-null  object
 2   EdType        31978 non-null  object
 3   occupation    31978 non-null  object
 4   capitalgain   31978 non-null  int64 
 5   capitalloss   31978 non-null  int64 
 6   hoursperweek  31978 non-null  int64 
 7   SalStat       31978 non-null  object
dtypes: int64(4), object(4)
memory usage: 2.0+ MB


In [31]:
df.columns

Index(['age', 'JobType', 'EdType', 'occupation', 'capitalgain', 'capitalloss',
       'hoursperweek', 'SalStat'],
      dtype='object')

In [32]:
df['JobType']=df['JobType'].astype('category')
df['JobType']=df['JobType'].cat.codes

df['EdType']=df['EdType'].astype('category')
df['EdType']=df['EdType'].cat.codes

df['SalStat']=df['SalStat'].astype('category')
df['SalStat']=df['SalStat'].cat.codes

df['occupation']=df['occupation'].astype('category')
df['occupation']=df['occupation'].cat.codes


In [33]:
df.head()

age  JobType  EdType  occupation  capitalgain  capitalloss  hoursperweek  \
0   45        4      11           1            0            0            28   
1   24        1      11           2            0            0            40   
2   44        4      15          10            0            0            40   
3   27        4       6           3            0            0            40   
4   20        4      15          12            0            0            35   

   SalStat  
0        1  
1        1  
2        0  
3        1  
4        1

In [34]:
df['SalStat'].unique()

array([1, 0], dtype=int8)

In [35]:
df.columns

Index(['age', 'JobType', 'EdType', 'occupation', 'capitalgain', 'capitalloss',
       'hoursperweek', 'SalStat'],
      dtype='object')

In [38]:
x=df[['age', 'JobType', 'EdType', 'occupation', 'capitalgain','capitalloss','hoursperweek']]
y=df[['SalStat']]

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [40]:
x_test

age  JobType  EdType  occupation  capitalgain  capitalloss  \
24244   25        7      15           1            0            0   
27422   53        4      11           3            0            0   
26290   56        1       9           4         7688            0   
23850   20        4      11           6            0            0   
23762   37        2       9          13            0            0   
...    ...      ...     ...         ...          ...          ...   
22867   31        4      11           7            0            0   
18611   30        4      11           4            0         1876   
25514   21        0      15           0            0            0   
690     40        4       9           8            0            0   
6474    23        4      15           1            0            0   

       hoursperweek  
24244            40  
27422            40  
26290            40  
23850            40  
23762            45  
...             ...  
22867            40  
18611            45  
25514            40  
690              37  
6474             20  

[6396 rows x 7 columns]

In [41]:
y_test

SalStat
24244        1
27422        0
26290        0
23850        1
23762        0
...        ...
22867        1
18611        1
25514        1
690          1
6474         1

[6396 rows x 1 columns]

In [42]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\TECQNIO\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\TECQNIO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [43]:
x_test.shape

(6396, 7)

In [44]:
y_predicted=model.predict(x_test)
y_predicted.shape

(6396,)

In [45]:
y_predicted[:10]

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int8)

In [46]:
y_test[:10]

SalStat
24244        1
27422        0
26290        0
23850        1
23762        0
9495         1
29483        1
20899        1
27368        1
8584         0

In [47]:
model.score(x_test,y_test)

0.7998749218261413